//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Sign In.
        /// </summary>
        internal static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        internal static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliates.
        /// </summary>
        internal static string Affiliates {
            get {
                return ResourceManager.GetString("Affiliates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        internal static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestselling.
        /// </summary>
        internal static string Bestselling {
            get {
                return ResourceManager.GetString("Bestselling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        internal static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call To Order.
        /// </summary>
        internal static string CallToOrder {
            get {
                return ResourceManager.GetString("CallToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum amount to proceed with your order is {OrderMin}..
        /// </summary>
        internal static string CartMinimum {
            get {
                return ResourceManager.GetString("CartMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with us:.
        /// </summary>
        internal static string ConnectWithUs {
            get {
                return ResourceManager.GetString("ConnectWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright ©.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        internal static string CouponCode {
            get {
                return ResourceManager.GetString("CouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Rating.
        /// </summary>
        internal static string CustomerRating {
            get {
                return ResourceManager.GetString("CustomerRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Reviews.
        /// </summary>
        internal static string CustomerReviews {
            get {
                return ResourceManager.GetString("CustomerReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        internal static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Locator.
        /// </summary>
        internal static string DealerLocator {
            get {
                return ResourceManager.GetString("DealerLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Login.
        /// </summary>
        internal static string DealerLogin {
            get {
                return ResourceManager.GetString("DealerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTIMATED ORDER TOTAL.
        /// </summary>
        internal static string EstimatedOrderTotal {
            get {
                return ResourceManager.GetString("EstimatedOrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Shipping.
        /// </summary>
        internal static string EstimatedShipping {
            get {
                return ResourceManager.GetString("EstimatedShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Tax.
        /// </summary>
        internal static string EstimatedTax {
            get {
                return ResourceManager.GetString("EstimatedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Shipping &amp; Tax.
        /// </summary>
        internal static string EstimateShippingAndTax {
            get {
                return ResourceManager.GetString("EstimateShippingAndTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Tax.
        /// </summary>
        internal static string EstimateTax {
            get {
                return ResourceManager.GetString("EstimateTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Items.
        /// </summary>
        internal static string FeaturedItems {
            get {
                return ResourceManager.GetString("FeaturedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        internal static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Certificates.
        /// </summary>
        internal static string GiftCerts {
            get {
                return ResourceManager.GetString("GiftCerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests &amp; New Customers.
        /// </summary>
        internal static string GuestsAndNewCustomers {
            get {
                return ResourceManager.GetString("GuestsAndNewCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest to Lowest.
        /// </summary>
        internal static string HighestToLowest {
            get {
                return ResourceManager.GetString("HighestToLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have forgotten your password, enter your username or email address below. Your password will be reset and a new password will be sent to you by email..
        /// </summary>
        internal static string IfYouForgotYourPassword {
            get {
                return ResourceManager.GetString("IfYouForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        internal static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number.
        /// </summary>
        internal static string ItemNumber {
            get {
                return ResourceManager.GetString("ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login for details.
        /// </summary>
        internal static string LoginForDetails {
            get {
                return ResourceManager.GetString("LoginForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to BuddLeather.com.
        /// </summary>
        internal static string LoginToOurSite {
            get {
                return ResourceManager.GetString("LoginToOurSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To Review this Product.
        /// </summary>
        internal static string LoginToReview {
            get {
                return ResourceManager.GetString("LoginToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to vote on this review.
        /// </summary>
        internal static string LoginToVote {
            get {
                return ResourceManager.GetString("LoginToVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest to Highest.
        /// </summary>
        internal static string LowestToHighest {
            get {
                return ResourceManager.GetString("LowestToHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Colors.
        /// </summary>
        internal static string MoreColors {
            get {
                return ResourceManager.GetString("MoreColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        internal static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Helpful.
        /// </summary>
        internal static string MostHelpful {
            get {
                return ResourceManager.GetString("MostHelpful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recent.
        /// </summary>
        internal static string MostRecent {
            get {
                return ResourceManager.GetString("MostRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        internal static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        internal static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews yet.
        /// </summary>
        internal static string NoReviewsYet {
            get {
                return ResourceManager.GetString("NoReviewsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Backorder.
        /// </summary>
        internal static string OnBackorder {
            get {
                return ResourceManager.GetString("OnBackorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        internal static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order SubTotal.
        /// </summary>
        internal static string OrderSubTotal {
            get {
                return ResourceManager.GetString("OrderSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Rating.
        /// </summary>
        internal static string OverallRating {
            get {
                return ResourceManager.GetString("OverallRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% of reviewers recommended this of product..
        /// </summary>
        internal static string PercentOfReviewersRecommendedThisProduct {
            get {
                return ResourceManager.GetString("PercentOfReviewersRecommendedThisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece.
        /// </summary>
        internal static string Piece {
            get {
                return ResourceManager.GetString("Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces.
        /// </summary>
        internal static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        internal static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (Least Expensive First).
        /// </summary>
        internal static string PriceLeastExpensive {
            get {
                return ResourceManager.GetString("PriceLeastExpensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (Most Expensive First).
        /// </summary>
        internal static string PriceMostExpensive {
            get {
                return ResourceManager.GetString("PriceMostExpensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read all of my reviews.
        /// </summary>
        internal static string ReadAllOfMyReviews {
            get {
                return ResourceManager.GetString("ReadAllOfMyReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read more.
        /// </summary>
        internal static string readmore {
            get {
                return ResourceManager.GetString("readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Viewed.
        /// </summary>
        internal static string RecentlyViewed {
            get {
                return ResourceManager.GetString("RecentlyViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        internal static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RecommendedNo {
            get {
                return ResourceManager.GetString("RecommendedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I recommend this product.
        /// </summary>
        internal static string RecommendedYes {
            get {
                return ResourceManager.GetString("RecommendedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;color:Red&quot;&gt;We were unable to access your information. An alert containing the information you entered has been sent to the help desk.&lt;/p&gt;&lt;p style=&quot;color:Red&quot;&gt;If you need immediate assistance, you can call the help desk at 800-332-BUDD or email us at &lt;a href=&quot;mailto:info@buddleather.com&quot;&gt;info@buddleather.com&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string RecoverFail {
            get {
                return ResourceManager.GetString("RecoverFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your username and password have been sent to you by email.&lt;/p&gt;&lt;p&gt;When you have received your password, &lt;a href=&quot;/login.aspx&quot;&gt;return to this page to login&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string RecoverSuccess {
            get {
                return ResourceManager.GetString("RecoverSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Customers.
        /// </summary>
        internal static string RegisteredCustomers {
            get {
                return ResourceManager.GetString("RegisteredCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products.
        /// </summary>
        internal static string RelatedProducts {
            get {
                return ResourceManager.GetString("RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me next time..
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Catalog.
        /// </summary>
        internal static string RequestCatalog {
            get {
                return ResourceManager.GetString("RequestCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Dealer Catalog.
        /// </summary>
        internal static string RequestDealerCatalog {
            get {
                return ResourceManager.GetString("RequestDealerCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username or email address to reset your password..
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        internal static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a review for a chance to win a $1000 gif card!.
        /// </summary>
        internal static string ReviewOffer {
            get {
                return ResourceManager.GetString("ReviewOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 review.
        /// </summary>
        internal static string ReviewOne {
            get {
                return ResourceManager.GetString("ReviewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reviews.
        /// </summary>
        internal static string ReviewsMany {
            get {
                return ResourceManager.GetString("ReviewsMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your review!.
        /// </summary>
        internal static string ReviewThank {
            get {
                return ResourceManager.GetString("ReviewThank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your review! Once approved, your review will appear on this page..
        /// </summary>
        internal static string ReviewThankModerated {
            get {
                return ResourceManager.GetString("ReviewThankModerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search our site....
        /// </summary>
        internal static string SearchOurSite {
            get {
                return ResourceManager.GetString("SearchOurSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see details.
        /// </summary>
        internal static string SeeDetails {
            get {
                return ResourceManager.GetString("SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping and returns.
        /// </summary>
        internal static string ShippingAndReturns {
            get {
                return ResourceManager.GetString("ShippingAndReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ShowPerPageLeft {
            get {
                return ResourceManager.GetString("ShowPerPageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per page.
        /// </summary>
        internal static string ShowPerPageRight {
            get {
                return ResourceManager.GetString("ShowPerPageRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in for faster checkout.
        /// </summary>
        internal static string SignInForFasterCheckout {
            get {
                return ResourceManager.GetString("SignInForFasterCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string SKU {
            get {
                return ResourceManager.GetString("SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Deals.
        /// </summary>
        internal static string SpecialDeals {
            get {
                return ResourceManager.GetString("SpecialDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        internal static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        internal static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required..
        /// </summary>
        internal static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was this review helpful to you?.
        /// </summary>
        internal static string WasThisReviewHelpfulToYou {
            get {
                return ResourceManager.GetString("WasThisReviewHelpfulToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale pricing is visible only to authorized customers.
        /// </summary>
        internal static string WholesaleOnlyPricing {
            get {
                return ResourceManager.GetString("WholesaleOnlyPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish List.
        /// </summary>
        internal static string WishList {
            get {
                return ResourceManager.GetString("WishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Review.
        /// </summary>
        internal static string WriteReview {
            get {
                return ResourceManager.GetString("WriteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create an account later.
        /// </summary>
        internal static string YouCanCreateAnAccountLater {
            get {
                return ResourceManager.GetString("YouCanCreateAnAccountLater", resourceCulture);
            }
        }
    }
}
